# Generated by Django 5.0.6 on 2024-05-17 18:21

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastros', '0017_remove_cadastro_admin_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CadastroEspelho',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('cadastros.cadastro',),
        ),
    ]
