# Generated by Django 5.0.6 on 2024-05-18 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cadastroAdimin", "0002_admin_cadastrovoluntarioespelho_membrofamiliaespelho"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Admin",
        ),
    ]
