# Generated by Django 5.0.6 on 2024-05-18 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cadastroAdimin", "0003_delete_admin"),
        ("cadastros", "0019_admin"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdminEspelho",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("cadastros.admin",),
        ),
    ]
