# Generated by Django 5.0.4 on 2024-05-08 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Admin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(
                        blank=True,
                        default="Sem nome",
                        help_text="Digite o nome aqui.",
                        max_length=100,
                        unique=True,
                        verbose_name="Nome",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=255, unique=True, verbose_name="E-mail"
                    ),
                ),
                ("senha", models.CharField(max_length=100)),
                ("confirmar_senha", models.CharField(max_length=100, null=True)),
                (
                    "telefone",
                    models.CharField(
                        blank=True, max_length=15, verbose_name="Telefone"
                    ),
                ),
                (
                    "cpf",
                    models.CharField(blank=True, max_length=14, verbose_name="CPF"),
                ),
                (
                    "descricao",
                    models.TextField(blank=True, null=True, verbose_name="Descrição"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CadastroVoluntario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(
                        blank=True,
                        default="Sem nome",
                        help_text="Digite o nome aqui.",
                        max_length=100,
                        unique=True,
                        verbose_name="Nome",
                    ),
                ),
                ("email", models.EmailField(max_length=255, verbose_name="E-mail")),
                ("senha", models.CharField(max_length=100)),
                ("confirmar_senha", models.CharField(max_length=100)),
                (
                    "telefone",
                    models.CharField(
                        blank=True, max_length=15, verbose_name="Telefone"
                    ),
                ),
                (
                    "cpf",
                    models.CharField(blank=True, max_length=14, verbose_name="CPF"),
                ),
                (
                    "descricao",
                    models.TextField(blank=True, null=True, verbose_name="Descrição"),
                ),
                (
                    "situacao",
                    models.CharField(
                        default="candidato", max_length=100, verbose_name="Situação"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Login",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=255, verbose_name="E-mail")),
                ("senha", models.CharField(max_length=100)),
                (
                    "opcao",
                    models.CharField(
                        choices=[("Adm", "Admin"), ("Func", "Funcionário")],
                        max_length=100,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Cadastro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(
                        blank=True,
                        default="Sem nome",
                        help_text="Digite o nome aqui.",
                        max_length=100,
                        null=True,
                        unique=True,
                        verbose_name="Nome",
                    ),
                ),
                (
                    "telefone",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Digite o número de telefone aqui.",
                        max_length=20,
                        null=True,
                        verbose_name="Telefone",
                    ),
                ),
                (
                    "celular",
                    models.CharField(
                        default="+00 (00) 00000-0000",
                        help_text="Digite o número de celular aqui.",
                        max_length=20,
                        verbose_name="Celular",
                    ),
                ),
                (
                    "sexo",
                    models.CharField(
                        choices=[("M", "Masculino"), ("F", "Feminino")],
                        max_length=1,
                        verbose_name="Sexo",
                    ),
                ),
                (
                    "data_nascimento",
                    models.DateField(verbose_name="Data de nascimento"),
                ),
                (
                    "endereco",
                    models.CharField(
                        blank=True,
                        default="Sem endereço",
                        help_text="Digite o endereço ",
                        max_length=200,
                        null=True,
                        verbose_name="Endereço",
                    ),
                ),
                (
                    "bairro",
                    models.CharField(
                        blank=True,
                        default="Sem bairro",
                        help_text="Digite o bairro aqui.",
                        max_length=100,
                        null=True,
                        verbose_name="Bairro",
                    ),
                ),
                (
                    "cidade",
                    models.CharField(
                        blank=True,
                        default="Sem cidade",
                        help_text="Digite a cidade aqui.",
                        max_length=100,
                        null=True,
                        verbose_name="Cidade",
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        blank=True,
                        default="Sem estado",
                        help_text="Digite o estado aqui.",
                        max_length=50,
                        null=True,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "cep",
                    models.CharField(
                        blank=True,
                        default="00000-000",
                        help_text="Digite o CEP aqui no formato XXXXX-XXX.",
                        max_length=9,
                        null=True,
                        verbose_name="CEP",
                    ),
                ),
                (
                    "complemento",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Digite o complemento do endereço aqui.",
                        max_length=200,
                        null=True,
                        verbose_name="Complemento",
                    ),
                ),
                (
                    "estado_civil",
                    models.CharField(max_length=100, verbose_name="Estado Civil"),
                ),
                ("rg", models.CharField(max_length=20, verbose_name="RG")),
                (
                    "DExp",
                    models.CharField(max_length=20, verbose_name="Data expiração"),
                ),
                (
                    "cpf",
                    models.CharField(
                        default="000.000.000-00", max_length=14, verbose_name="CPF"
                    ),
                ),
                ("escolaridade", models.CharField(max_length=100, null=True)),
                (
                    "profissao",
                    models.CharField(max_length=100, verbose_name="Profissão"),
                ),
                ("renda", models.FloatField(null=True, verbose_name="Renda")),
                (
                    "ocupacao_atual",
                    models.CharField(
                        max_length=100, null=True, verbose_name="Ocupação atual"
                    ),
                ),
                (
                    "beneficio_Gov",
                    models.CharField(
                        choices=[
                            ("Fed", "Federais"),
                            ("Est", "Estaduais"),
                            ("Mun", "Municipais"),
                            ("BF", "Bolsa Familia"),
                            ("BPC", "Benefício de Prestação Continuada"),
                            ("PETI", "Programa de Erradicação do Trabalho Infantil"),
                            ("O", "Outros"),
                        ],
                        max_length=4,
                        null=True,
                    ),
                ),
                (
                    "renda_gov",
                    models.FloatField(null=True, verbose_name="Renda do governo"),
                ),
                (
                    "minha_moradia",
                    models.CharField(
                        choices=[
                            ("A", "Aluguel"),
                            ("C", "Cessão"),
                            ("F", "Financiada"),
                            ("I", "Invasão"),
                            ("P", "Própria"),
                        ],
                        max_length=1,
                        verbose_name="Estado da moradia",
                    ),
                ),
                (
                    "minha_morada",
                    models.CharField(
                        choices=[
                            ("Alvenida", "Alvenida"),
                            ("Papelão", "Papelão"),
                            ("Palafita", "Palafita"),
                            ("Madeira", "Madeira"),
                            ("Lona", "Lona"),
                            ("Plástico", "Plástico"),
                        ],
                        max_length=10,
                        verbose_name="Detalhes da moradia",
                    ),
                ),
                (
                    "quantidade_comodos",
                    models.IntegerField(default=0, verbose_name="Quantidade de cômodo"),
                ),
                (
                    "quartos",
                    models.IntegerField(verbose_name="Quantidade de quarto(s)"),
                ),
                ("sala", models.IntegerField(verbose_name="Quantidade de sala(s)")),
                (
                    "cozinha",
                    models.IntegerField(verbose_name="Quantidade de vozinha(s)"),
                ),
                (
                    "banheiro",
                    models.IntegerField(verbose_name="Quantidade de banheiro(s)"),
                ),
                (
                    "agua_encanada",
                    models.BooleanField(default=False, verbose_name="Água encanada"),
                ),
                ("esgoto", models.BooleanField(default=False, verbose_name="Esgoto")),
                ("energia", models.BooleanField(default=False, verbose_name="Energia")),
                (
                    "coleta_lixo",
                    models.BooleanField(default=False, verbose_name="Coleta de lixo"),
                ),
                (
                    "finished_at",
                    models.DateField(null=True, verbose_name="Data finalizado"),
                ),
                (
                    "admin",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cadastros.admin",
                    ),
                ),
                (
                    "candidato",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cadastros.cadastrovoluntario",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Atualizar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("idCandidato", models.IntegerField(default=0)),
                ("idCrianca", models.IntegerField(default=0)),
                (
                    "criancas",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cadastros.cadastro",
                    ),
                ),
                (
                    "candidato",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cadastros.cadastrovoluntario",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MembroFamilia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(
                        blank=True,
                        default="Sem nome",
                        help_text="Digite o nome aqui.",
                        max_length=100,
                        null=True,
                        unique=True,
                        verbose_name="Nome",
                    ),
                ),
                (
                    "sexo",
                    models.CharField(
                        choices=[("M", "Masculino"), ("F", "Feminino")],
                        max_length=1,
                        verbose_name="Sexo",
                    ),
                ),
                (
                    "data_nascimento",
                    models.DateField(verbose_name="Data de nascimento"),
                ),
                (
                    "estado_civil",
                    models.CharField(max_length=100, verbose_name="Estado Civil"),
                ),
                ("vinculo_familia", models.CharField(max_length=100, null=True)),
                (
                    "telefone",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Digite o número de telefone aqui.",
                        max_length=20,
                        null=True,
                        verbose_name="Telefone",
                    ),
                ),
                (
                    "celular",
                    models.CharField(
                        default="+00 (00) 00000-0000",
                        help_text="Digite o número de celular aqui.",
                        max_length=20,
                        verbose_name="Celular",
                    ),
                ),
                ("escolaridade", models.CharField(max_length=100, null=True)),
                (
                    "profissao",
                    models.CharField(max_length=100, verbose_name="Profissão"),
                ),
                ("renda", models.FloatField(null=True, verbose_name="Renda")),
                (
                    "ocupacao_atual",
                    models.CharField(
                        max_length=100, null=True, verbose_name="Ocupação atual"
                    ),
                ),
                (
                    "cadastro",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="membroFamilia",
                        to="cadastros.cadastro",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Verificar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("idAdim", models.IntegerField(default=0)),
                ("idCandidato", models.IntegerField(default=0)),
                (
                    "admin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cadastros.admin",
                    ),
                ),
                (
                    "candidato",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cadastros.cadastrovoluntario",
                    ),
                ),
            ],
        ),
    ]
