# Generated by Django 5.0.4 on 2024-05-09 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadastros", "0003_alter_cadastrovoluntario_situacao"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cadastrovoluntario",
            name="email",
            field=models.EmailField(max_length=255, unique=True, verbose_name="E-mail"),
        ),
    ]
