# Generated by Django 5.0.4 on 2024-05-09 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cadastros", "0004_alter_cadastrovoluntario_email"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="admin",
            name="descricao",
        ),
    ]
