# Generated by Django 5.0.4 on 2024-05-09 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cadastros", "0005_remove_admin_descricao"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="admin",
            name="confirmar_senha",
        ),
    ]
