# Generated by Django 5.0.4 on 2024-05-10 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cadastros", "0009_alter_cadastrovoluntario_situacao"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cadastro",
            old_name="admin",
            new_name="admin_id",
        ),
        migrations.RenameField(
            model_name="cadastro",
            old_name="candidato",
            new_name="funcionario_id",
        ),
        migrations.DeleteModel(
            name="Verificar",
        ),
    ]
