# Generated by Django 5.0.4 on 2024-05-13 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadastros", "0010_rename_admin_cadastro_admin_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cadastro",
            name="cozinha",
            field=models.IntegerField(verbose_name="Quantidade de cozinha(s)"),
        ),
        migrations.AlterField(
            model_name="membrofamilia",
            name="nome",
            field=models.CharField(
                blank=True,
                default="Sem nome",
                help_text="Digite o nome aqui.",
                max_length=100,
                null=True,
                verbose_name="Nome",
            ),
        ),
    ]
