# Generated by Django 5.0.4 on 2024-05-13 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadastros", "0011_alter_cadastro_cozinha_alter_membrofamilia_nome"),
    ]

    operations = [
        migrations.AlterField(
            model_name="admin",
            name="email",
            field=models.EmailField(
                error_messages={
                    "blank": "Este campo não pode ficar em branco.",
                    "invalid": "O valor fornecido é inválido, verifique se tem @.",
                },
                help_text="Digite o E-mail aqui.",
                max_length=255,
                unique=True,
                verbose_name="E-mail",
            ),
        ),
        migrations.AlterField(
            model_name="admin",
            name="nome",
            field=models.CharField(
                default="Sem nome",
                help_text="Digite o nome aqui.",
                max_length=100,
                verbose_name="Nome",
            ),
        ),
    ]
