# Generated by Django 5.0.4 on 2024-05-14 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadastros", "0012_alter_admin_email_alter_admin_nome"),
    ]

    operations = [
        migrations.AlterField(
            model_name="admin",
            name="cpf",
            field=models.CharField(
                blank=True,
                help_text="Digite seu CPF aqui.",
                max_length=14,
                unique=True,
                verbose_name="CPF",
            ),
        ),
        migrations.AlterField(
            model_name="admin",
            name="telefone",
            field=models.CharField(
                blank=True,
                help_text="Digite seu Telefone aqui. (21) 90000-0000",
                max_length=15,
                verbose_name="Telefone",
            ),
        ),
    ]
