# Generated by Django 5.0.6 on 2024-05-15 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadastros", "0014_alter_admin_cpf_alter_admin_nome_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cadastro",
            name="DExp",
            field=models.CharField(
                help_text="Diga a data de expedição do documento",
                max_length=20,
                verbose_name="Data expiração",
            ),
        ),
        migrations.AlterField(
            model_name="cadastro",
            name="bairro",
            field=models.CharField(
                blank=True,
                help_text="Digite o bairro aqui.",
                max_length=100,
                null=True,
                verbose_name="Bairro",
            ),
        ),
        migrations.AlterField(
            model_name="cadastro",
            name="celular",
            field=models.CharField(
                blank=True,
                help_text="Digite seu Telefone aqui. como no exemplo: (21) 9xxxx-xxxx",
                max_length=15,
                verbose_name="Telefone",
            ),
        ),
        migrations.AlterField(
            model_name="cadastro",
            name="cep",
            field=models.CharField(
                blank=True,
                help_text="Digite o CEP aqui no formato XXXXX-XXX.",
                max_length=9,
                null=True,
                verbose_name="CEP",
            ),
        ),
        migrations.AlterField(
            model_name="cadastro",
            name="cidade",
            field=models.CharField(
                help_text="Digite a cidade aqui.",
                max_length=100,
                null=True,
                verbose_name="Cidade",
            ),
        ),
        migrations.AlterField(
            model_name="cadastro",
            name="complemento",
            field=models.CharField(
                blank=True,
                help_text="Digite o complemento do endereço aqui.",
                max_length=200,
                null=True,
                verbose_name="Complemento",
            ),
        ),
        migrations.AlterField(
            model_name="cadastro",
            name="cpf",
            field=models.CharField(
                blank=True,
                help_text="Digite seu CPF aqui modelo: 000.000.000-00",
                max_length=14,
                unique=True,
                verbose_name="CPF",
            ),
        ),
        migrations.AlterField(
            model_name="cadastro",
            name="data_nascimento",
            field=models.DateField(
                help_text="Data de nascimento", verbose_name="Data de nascimento"
            ),
        ),
        migrations.AlterField(
            model_name="cadastro",
            name="endereco",
            field=models.CharField(
                help_text="Digite o endereço ",
                max_length=200,
                null=True,
                verbose_name="Endereço",
            ),
        ),
        migrations.AlterField(
            model_name="cadastro",
            name="estado",
            field=models.CharField(
                blank=True,
                help_text="Digite o estado aqui.",
                max_length=50,
                null=True,
                verbose_name="Estado",
            ),
        ),
        migrations.AlterField(
            model_name="cadastro",
            name="nome",
            field=models.CharField(
                help_text="Digite o nome aqui.", max_length=100, verbose_name="Nome"
            ),
        ),
        migrations.AlterField(
            model_name="cadastro",
            name="telefone",
            field=models.CharField(
                help_text="Digite o número de telefone aqui.",
                max_length=20,
                verbose_name="Telefone",
            ),
        ),
        migrations.AlterField(
            model_name="cadastrovoluntario",
            name="cpf",
            field=models.CharField(
                blank=True,
                help_text="Digite seu CPF aqui modelo: 000.000.000-00",
                max_length=14,
                unique=True,
                verbose_name="CPF",
            ),
        ),
        migrations.AlterField(
            model_name="cadastrovoluntario",
            name="telefone",
            field=models.CharField(
                blank=True,
                help_text="Digite seu Telefone aqui. como no exemplo: (21) 9xxxx-xxxx",
                max_length=15,
                verbose_name="Telefone",
            ),
        ),
        migrations.AlterField(
            model_name="membrofamilia",
            name="celular",
            field=models.CharField(
                blank=True,
                help_text="Digite seu Telefone aqui. como no exemplo: (21) 9xxxx-xxxx",
                max_length=15,
                verbose_name="Telefone",
            ),
        ),
        migrations.AlterField(
            model_name="membrofamilia",
            name="nome",
            field=models.CharField(
                help_text="Digite o nome aqui.", max_length=100, verbose_name="Nome"
            ),
        ),
        migrations.AlterField(
            model_name="membrofamilia",
            name="telefone",
            field=models.CharField(
                blank=True,
                help_text="Digite o número de telefone aqui.",
                max_length=20,
                null=True,
                verbose_name="Telefone",
            ),
        ),
    ]
