# Generated by Django 5.0.6 on 2024-05-15 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0015_alter_cadastro_dexp_alter_cadastro_bairro_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='cpf',
            field=models.CharField(blank=True, help_text='Digite seu CPF aqui modelo: 000.000.000-00', max_length=14, unique=True, verbose_name='CPF'),
        ),
    ]
