# Generated by Django 5.0.6 on 2024-05-16 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0016_alter_admin_cpf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cadastro',
            name='admin_id',
        ),
        migrations.RemoveField(
            model_name='cadastro',
            name='funcionario_id',
        ),
    ]
