# Generated by Django 5.0.6 on 2024-05-18 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cadastros", "0017_remove_cadastro_admin_id_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Admin",
        ),
    ]
