# Generated by Django 5.0.6 on 2024-05-18 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadastros", "0019_admin"),
    ]

    operations = [
        migrations.AddField(
            model_name="admin",
            name="situacao",
            field=models.CharField(
                default="Candidato", max_length=100, verbose_name="Situação"
            ),
        ),
    ]
