# Generated by Django 5.0.4 on 2024-04-21 00:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cadastro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, null=True)),
                ('cpf', models.CharField(max_length=11, null=True)),
                ('data_de_nascimento', models.DateField(blank=True, null=True)),
                ('is_published', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='MembroFamilia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('sexo', models.CharField(choices=[('feminino', 'Feminino'), ('masculino', 'Masculino'), ('outros', 'Outros')], max_length=10)),
                ('is_published', models.BooleanField(default=True)),
                ('cadastro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membrosFamilia', to='CadCliente.cadastro')),
            ],
        ),
    ]
