# Generated by Django 5.0.4 on 2024-04-13 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CadCliente', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastro',
            name='nome',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
