# Generated by Django 5.0.4 on 2024-04-13 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CadCliente', '0002_alter_cadastro_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastro',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
    ]
