# Generated by Django 5.0.4 on 2024-04-13 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CadCliente', '0003_alter_cadastro_is_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadastro',
            name='idade',
            field=models.DateField(null=True),
        ),
    ]
