# Generated by Django 5.0.4 on 2024-04-13 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CadCliente', '0004_cadastro_idade'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cadastro',
            old_name='idade',
            new_name='data_de_nascimento',
        ),
    ]
