# Generated by Django 5.0.4 on 2024-04-13 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CadCliente', '0005_rename_idade_cadastro_data_de_nascimento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cadastro',
            name='data_de_nascimento',
        ),
    ]
