# Generated by Django 5.0.4 on 2024-04-13 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CadCliente', '0007_cadastro_data_de_nascimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastro',
            name='data_de_nascimento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
