# Generated by Django 5.0.4 on 2024-04-14 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CadCliente', '0008_alter_cadastro_data_de_nascimento'),
    ]

    operations = [
        migrations.CreateModel(
            name='MembroFamilia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('sexo', models.CharField(max_length=10)),
                ('cadastro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CadCliente.cadastro')),
            ],
        ),
    ]
