# Generated by Django 5.0.4 on 2024-04-14 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CadCliente', '0010_alter_membrofamilia_sexo'),
    ]

    operations = [
        migrations.AddField(
            model_name='membrofamilia',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
    ]
