# Generated by Django 5.0.4 on 2024-04-14 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CadCliente', '0011_membrofamilia_is_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membrofamilia',
            name='cadastro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membrosFamilia', to='CadCliente.cadastro'),
        ),
    ]
