# Generated by Django 5.0.4 on 2024-04-14 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CadCliente', '0012_alter_membrofamilia_cadastro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membrofamilia',
            name='sexo',
            field=models.CharField(choices=[('Feminino', 'Feminino'), ('Masculino', 'Masculino'), ('Outros', 'Outros')], max_length=10),
        ),
    ]
