# Generated by Django 5.0.4 on 2024-04-14 22:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CadCliente', '0014_cadastro_nomefamilia_cadastro_sexofamilia_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cadastro',
            name='nomeFamilia',
        ),
        migrations.RemoveField(
            model_name='cadastro',
            name='sexoFamilia',
        ),
        migrations.CreateModel(
            name='MembroFamilia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('sexo', models.CharField(choices=[('feminino', 'Feminino'), ('masculino', 'Masculino'), ('outros', 'Outros')], max_length=10)),
                ('is_published', models.BooleanField(default=True)),
                ('cadastro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CadCliente.cadastro')),
            ],
        ),
    ]
